version: "3"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'


services:
  mysql:
    image: mysql:8.0.21
    container_name: gva-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'gin_class' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: '123456' # root管理员用户密码
    networks:
      network:
        ipv4_address: 177.7.0.13

#  redis:
#    image: redis:6.0.6
#    container_name: gva-redis # 容器名
#    restart: always
#    ports:
#      - '16379:6379'
#    networks:
#      network:
#        ipv4_address: 177.7.0.14


  server:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
    image: tlqjxd/gin_class_server:v1.0.2
    container_name: gva-server
    restart: always
    environment:
      dsn: root:123456@tcp(177.7.0.13:3306)/gin_class?charset=utf8mb4&parseTime=True&loc=Local
      mq: mq.nlecloud.com:1883
    ports:
      - '8888:8888'
    depends_on:
      - mysql
#      - redis
    links:
      - mysql
#      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12
