basePath: /
definitions:
  request.Coap:
    properties:
      datas:
        additionalProperties:
          items:
            type: object
          type: array
        type: object
      host:
        type: string
      path:
        type: string
    type: object
  request.Login:
    properties:
      captcha:
        type: string
      captcha_id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample Server pets
  title: Swagger Example API
  version: 0.0.1
paths:
  /base/captcha:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"验证码获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 生成验证码
      tags:
      - Base
  /base/login:
    post:
      parameters:
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - Base
  /coap/send:
    post:
      parameters:
      - description: IP, path, 数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Coap'
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"发送成功"}'
          schema:
            type: string
      security:
      - application/json: []
      summary: 发送Coap
      tags:
      - Coap
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
